export const LANGUAGES = [
  { value: "javascript", label: "JavaScript" },
  { value: "dart", label: "Dart" },
  { value: "python", label: "Python" },
  { value: "typescript", label: "TypeScript" },
  { value: "c", label: "C" },
  { value: "java", label: "Java" },
  { value: "cpp", label: "C++" },
  { value: "cs", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "go", label: "Go" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "scala", label: "Scala" },
];
